/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SaxKeys_aliases.h"
#include "Clock_1.h"
#include "Button_Switch.h"
#include "KeyNote_Low.h"
#include "KeyNote_High.h"
#include "Waveform_Send.h"
#include "Fs_aliases.h"
#include "Fs.h"
#include "Waveform_ISR.h"
#include "Wave_Out.h"
#include "DACBuffer.h"
#include "Waveform_aliases.h"
#include "Waveform.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "SPIM_1.h"
#include "SPIM_1_PVT.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "SS_aliases.h"
#include "SS.h"
#include "DC_aliases.h"
#include "DC.h"
#include "RESET_aliases.h"
#include "RESET.h"
#include "LED_aliases.h"
#include "LED.h"
#include "ADC_VolumePedal.h"
#include "VolumePedalIn_aliases.h"
#include "VolumePedalIn.h"
#include "ReadInputs.h"
#include "Inputs.h"
#include "UpdateNote.h"
#include "NewNote.h"
#include "Output_LED_aliases.h"
#include "Control_Reg_1.h"
#include "Control_Reg_2.h"
#include "Wave_Out_DMA_dma.h"
#include "Wave_Out_VDAC8.h"
#include "Wave_Out_IntClock.h"
#include "SPIM_1_IntClock.h"
#include "ADC_VolumePedal_AMux.h"
#include "ADC_VolumePedal_Ext_CP_Clk.h"
#include "ADC_VolumePedal_IRQ.h"
#include "ADC_VolumePedal_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

